### ISSUE TITLE
Warn before build/upload that `platformio` isn't in PATH

### ISSUE THREAD

**Issue by ivankravets** [vigetlabs/platomformio#15] opened 2015-12-07 14:50 UTC
Friends,

This issue is improvement for #14. Need to implement logic with finding `platformio` in environment PATH(including `atom.config.get('platomformio.environPath')`) before any CMD/RUN operation.

I propose to show ALERT/WARNING that `platformio` isn't found in current env PATH and need go to package's settings and specify valid PATH.

In 70-80% cases there no need to specify PATH in settings because users install @PlatformIO in global system. 

Ping @efatsi , @RomFouq

**Comment by efatsi** [comment] 2015-12-07 14:57
@ivankravets the package already warns if the `platformio` command is unavailable. You can reproduce this by adjusting your package's PATH setting to be incorrect, and then try to build a project. You should see this warning:
![image](https://cloud.githubusercontent.com/assets/1410181/11629861/d9a8cfcc-9cb7-11e5-937e-586b08123273.png)

It looks like #14 was perhaps another issue.

For instance, my `platformio` lives at `/usr/local/bin/platformio`. If I set my package PATH setting to `usr/local/bin`, I get the `scons aren't installed properly` warning.

**Comment by ivankravets** [comment] 2015-12-07 15:07
@efatsi  I saw it yesterday. It looks unclear for end user :( Maybe, need rephrase it? Like:

```
Could not run `platformio` because it has not been found in any of directories from environment PATH (%HERE_CURRENT_PATH)

Please go to package's settings and specify environment PATH using all guidelines . 
```

Please correct it because my English isn't so good. Thanks.

---

Also, this error is linked with ALL problems for CMD command. It's not related to invalid PATH in all cases. For example, some errors with arguments to run `platformio` will raise here.

**Comment by ivankravets** [comment] 2015-12-07 15:11
> For instance, my platformio lives at /usr/local/bin/platformio. If I set my package PATH setting to usr/local/bin, I get the scons aren't installed properly warning.

Here is another problem. If `SCons` is installed in your system, PlatformIO will use it. It looks that `scons` and `platformio` live in the different places. If `scons` isn't installed in your system, then `platformio` will install it "near platformio".

---

See guidelines here https://github.com/vigetlabs/platomformio/blob/master/lib/platomformio.coffee#L16.
Again, maybe need to rephrase it that here user MUST input only `Paste here the result of`echo $PATH`(Unix) /`echo %PATH%`(Windows) command by typing into your terminal`. No single directory...

**Comment by efatsi** [comment] 2015-12-07 15:51
I think I'm going to close this issue until another PATH problem comes up. I've updated the README to instruct users to configure the PATH setting. If that's followed, then none of these issues should ever happen (hopefully).

**Closed as completed by efatsi** 2015-12-07 15:51 UTC
Labels: enhancement

**Comment by ivankravets** [comment] 2015-12-07 16:02
Ok, I've just removed confused wording about "directory where is `platformio`". See https://github.com/vigetlabs/platomformio/commit/b0d7a053f02552e52e92d41d492496e86a9fdda1

Maybe, 0.6.4?

**Comment by efatsi** [comment] 2015-12-07 17:03
@ivankravets this is interesting:

```
$ which platformio
/usr/local/bin/platformio
$ which scons
/usr/local/bin/scons
```

However if I set the Enviornment PATH to `/usr/local/bin`, I get the `scons aren't installed properly` PlatformIO error message.

Same error if PATH is set to `/bin:/usr/local/bin`

If the PATH is set to `/usr/bin:/usr/local/bin`, I get a different error: `scons: *** [size] No such file or directory`.

For me at least, I need it to be `/bin:/usr/bin:/usr/local/bin`.

**Comment by ivankravets** [comment] 2015-12-07 18:49
@efatsi hm... Looks like `scons` uses some things from system. OK, I've just modified env.path. See https://github.com/vigetlabs/platomformio/commit/3cb39e03924c6c08ecfe3ce23ab28aefa724d426

In this case, only if user's settings are available, then use `+ ":" + options.env.PATH`

**Comment by ivankravets** [comment] 2015-12-07 19:27
@efatsi could you release 0.6.4? I'll ask Slav to try it https://viget.com/extend/arduino-development-in-atom-editor#comment-2398267868

**Comment by efatsi** [comment] 2015-12-07 21:29
Pushed up `0.6.5`. However, I don't think that's the ultimate fix for the issue that people are seeing. They should be able to resolve the `scons` issue themselves with the proper PATH setting.

**Comment by ivankravets** [comment] 2015-12-07 21:38
@efatsi I agree with you. However, this build resolves issue when user inputs only "path to real single directory where platformio is located". In this case, package will add automatically system PATH.

Thanks! Why 0.6.5? :smile: Where is 0.6.4?

**Comment by efatsi** [comment] 2015-12-07 21:47
Had to leave 0.6.4 behind. The "Atom Package Manager" is a very finicky tool, it fails unless it can update the package.json, create a new git tag, push the new commit to github, and then push the new package version to Atom. Probably could have figured it out, but it was giving me a bunch of trouble so I just jumped to 0.6.5.

**Comment by ivankravets** [comment] 2015-12-07 21:49
Just tweeted https://twitter.com/platformio_org/status/673981939762765824

Let wait for the feedback.
